name: Lint Code Base

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint protobuf
        uses: plexsystems/protolint-action@v0.7.0
